# Generated by Django 3.0.8 on 2020-07-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200704_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_opt',
        ),
        migrations.AddField(
            model_name='option',
            name='correct_opt',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
