# Generated by Django 3.0.8 on 2020-07-04 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200704_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Subject'),
            preserve_default=False,
        ),
    ]
