# Generated by Django 3.0.8 on 2020-07-04 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_option_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='subject',
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Question'),
            preserve_default=False,
        ),
    ]
