# Generated by Django 3.0.8 on 2020-07-04 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200704_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='correct_opt',
            field=models.CharField(default=4, max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.Question'),
        ),
    ]
