# Generated by Django 3.0.8 on 2020-07-04 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200704_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='correct_opt',
        ),
    ]
